// Code generated by mockery. DO NOT EDIT.

package locales_mocks

import mock "github.com/stretchr/testify/mock"

// MockLoader is an autogenerated mock type for the Loader type
type MockLoader struct {
	mock.Mock
}

type MockLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoader) EXPECT() *MockLoader_Expecter {
	return &MockLoader_Expecter{mock: &_m.Mock}
}

// LoadMessage provides a mock function with given fields: filepath
func (_m *MockLoader) LoadMessage(filepath string) ([]byte, error) {
	ret := _m.Called(filepath)

	if len(ret) == 0 {
		panic("no return value specified for LoadMessage")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(filepath)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(filepath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filepath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoader_LoadMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadMessage'
type MockLoader_LoadMessage_Call struct {
	*mock.Call
}

// LoadMessage is a helper method to define mock.On call
//   - filepath string
func (_e *MockLoader_Expecter) LoadMessage(filepath interface{}) *MockLoader_LoadMessage_Call {
	return &MockLoader_LoadMessage_Call{Call: _e.mock.On("LoadMessage", filepath)}
}

func (_c *MockLoader_LoadMessage_Call) Run(run func(filepath string)) *MockLoader_LoadMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLoader_LoadMessage_Call) Return(_a0 []byte, _a1 error) *MockLoader_LoadMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoader_LoadMessage_Call) RunAndReturn(run func(string) ([]byte, error)) *MockLoader_LoadMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoader creates a new instance of MockLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoader {
	mock := &MockLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
