// Code generated by mockery. DO NOT EDIT.

package locales_mocks

import mock "github.com/stretchr/testify/mock"

// MockLoaderFunc is an autogenerated mock type for the LoaderFunc type
type MockLoaderFunc struct {
	mock.Mock
}

type MockLoaderFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoaderFunc) EXPECT() *MockLoaderFunc_Expecter {
	return &MockLoaderFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockLoaderFunc) Execute(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoaderFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockLoaderFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 string
func (_e *MockLoaderFunc_Expecter) Execute(_a0 interface{}) *MockLoaderFunc_Execute_Call {
	return &MockLoaderFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockLoaderFunc_Execute_Call) Run(run func(_a0 string)) *MockLoaderFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLoaderFunc_Execute_Call) Return(_a0 []byte, _a1 error) *MockLoaderFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoaderFunc_Execute_Call) RunAndReturn(run func(string) ([]byte, error)) *MockLoaderFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoaderFunc creates a new instance of MockLoaderFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoaderFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoaderFunc {
	mock := &MockLoaderFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
