// Code generated by mockery. DO NOT EDIT.

package locales_mocks

import (
	embed "embed"

	i18n "github.com/nicksnyder/go-i18n/v2/i18n"

	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Bundle provides a mock function with no fields
func (_m *MockManager) Bundle() *i18n.Bundle {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bundle")
	}

	var r0 *i18n.Bundle
	if rf, ok := ret.Get(0).(func() *i18n.Bundle); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*i18n.Bundle)
		}
	}

	return r0
}

// MockManager_Bundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bundle'
type MockManager_Bundle_Call struct {
	*mock.Call
}

// Bundle is a helper method to define mock.On call
func (_e *MockManager_Expecter) Bundle() *MockManager_Bundle_Call {
	return &MockManager_Bundle_Call{Call: _e.mock.On("Bundle")}
}

func (_c *MockManager_Bundle_Call) Run(run func()) *MockManager_Bundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Bundle_Call) Return(_a0 *i18n.Bundle) *MockManager_Bundle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_Bundle_Call) RunAndReturn(run func() *i18n.Bundle) *MockManager_Bundle_Call {
	_c.Call.Return(run)
	return _c
}

// LoadEmbeddedTranslations provides a mock function with given fields: embeddedFS, directory
func (_m *MockManager) LoadEmbeddedTranslations(embeddedFS embed.FS, directory string) error {
	ret := _m.Called(embeddedFS, directory)

	if len(ret) == 0 {
		panic("no return value specified for LoadEmbeddedTranslations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(embed.FS, string) error); ok {
		r0 = rf(embeddedFS, directory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_LoadEmbeddedTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadEmbeddedTranslations'
type MockManager_LoadEmbeddedTranslations_Call struct {
	*mock.Call
}

// LoadEmbeddedTranslations is a helper method to define mock.On call
//   - embeddedFS embed.FS
//   - directory string
func (_e *MockManager_Expecter) LoadEmbeddedTranslations(embeddedFS interface{}, directory interface{}) *MockManager_LoadEmbeddedTranslations_Call {
	return &MockManager_LoadEmbeddedTranslations_Call{Call: _e.mock.On("LoadEmbeddedTranslations", embeddedFS, directory)}
}

func (_c *MockManager_LoadEmbeddedTranslations_Call) Run(run func(embeddedFS embed.FS, directory string)) *MockManager_LoadEmbeddedTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(embed.FS), args[1].(string))
	})
	return _c
}

func (_c *MockManager_LoadEmbeddedTranslations_Call) Return(_a0 error) *MockManager_LoadEmbeddedTranslations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_LoadEmbeddedTranslations_Call) RunAndReturn(run func(embed.FS, string) error) *MockManager_LoadEmbeddedTranslations_Call {
	_c.Call.Return(run)
	return _c
}

// LoadTranslations provides a mock function with given fields: directory, loaderFunc
func (_m *MockManager) LoadTranslations(directory string, loaderFunc func(string) ([]byte, error)) error {
	ret := _m.Called(directory, loaderFunc)

	if len(ret) == 0 {
		panic("no return value specified for LoadTranslations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(string) ([]byte, error)) error); ok {
		r0 = rf(directory, loaderFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_LoadTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTranslations'
type MockManager_LoadTranslations_Call struct {
	*mock.Call
}

// LoadTranslations is a helper method to define mock.On call
//   - directory string
//   - loaderFunc func(string)([]byte , error)
func (_e *MockManager_Expecter) LoadTranslations(directory interface{}, loaderFunc interface{}) *MockManager_LoadTranslations_Call {
	return &MockManager_LoadTranslations_Call{Call: _e.mock.On("LoadTranslations", directory, loaderFunc)}
}

func (_c *MockManager_LoadTranslations_Call) Run(run func(directory string, loaderFunc func(string) ([]byte, error))) *MockManager_LoadTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(string) ([]byte, error)))
	})
	return _c
}

func (_c *MockManager_LoadTranslations_Call) Return(_a0 error) *MockManager_LoadTranslations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_LoadTranslations_Call) RunAndReturn(run func(string, func(string) ([]byte, error)) error) *MockManager_LoadTranslations_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterTranslations provides a mock function with given fields: module, translations
func (_m *MockManager) RegisterTranslations(module string, translations map[string]map[string]string) {
	_m.Called(module, translations)
}

// MockManager_RegisterTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterTranslations'
type MockManager_RegisterTranslations_Call struct {
	*mock.Call
}

// RegisterTranslations is a helper method to define mock.On call
//   - module string
//   - translations map[string]map[string]string
func (_e *MockManager_Expecter) RegisterTranslations(module interface{}, translations interface{}) *MockManager_RegisterTranslations_Call {
	return &MockManager_RegisterTranslations_Call{Call: _e.mock.On("RegisterTranslations", module, translations)}
}

func (_c *MockManager_RegisterTranslations_Call) Run(run func(module string, translations map[string]map[string]string)) *MockManager_RegisterTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]map[string]string))
	})
	return _c
}

func (_c *MockManager_RegisterTranslations_Call) Return() *MockManager_RegisterTranslations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_RegisterTranslations_Call) RunAndReturn(run func(string, map[string]map[string]string)) *MockManager_RegisterTranslations_Call {
	_c.Run(run)
	return _c
}

// SetLocale provides a mock function with given fields: locale
func (_m *MockManager) SetLocale(locale string) {
	_m.Called(locale)
}

// MockManager_SetLocale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLocale'
type MockManager_SetLocale_Call struct {
	*mock.Call
}

// SetLocale is a helper method to define mock.On call
//   - locale string
func (_e *MockManager_Expecter) SetLocale(locale interface{}) *MockManager_SetLocale_Call {
	return &MockManager_SetLocale_Call{Call: _e.mock.On("SetLocale", locale)}
}

func (_c *MockManager_SetLocale_Call) Run(run func(locale string)) *MockManager_SetLocale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_SetLocale_Call) Return() *MockManager_SetLocale_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_SetLocale_Call) RunAndReturn(run func(string)) *MockManager_SetLocale_Call {
	_c.Run(run)
	return _c
}

// Translate provides a mock function with given fields: lang, key, args
func (_m *MockManager) Translate(lang string, key string, args map[string]interface{}) string {
	ret := _m.Called(lang, key, args)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, map[string]interface{}) string); ok {
		r0 = rf(lang, key, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockManager_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockManager_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - lang string
//   - key string
//   - args map[string]interface{}
func (_e *MockManager_Expecter) Translate(lang interface{}, key interface{}, args interface{}) *MockManager_Translate_Call {
	return &MockManager_Translate_Call{Call: _e.mock.On("Translate", lang, key, args)}
}

func (_c *MockManager_Translate_Call) Run(run func(lang string, key string, args map[string]interface{})) *MockManager_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockManager_Translate_Call) Return(_a0 string) *MockManager_Translate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_Translate_Call) RunAndReturn(run func(string, string, map[string]interface{}) string) *MockManager_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateFunc provides a mock function with given fields: lang
func (_m *MockManager) TranslateFunc(lang string) func(string, map[string]interface{}) string {
	ret := _m.Called(lang)

	if len(ret) == 0 {
		panic("no return value specified for TranslateFunc")
	}

	var r0 func(string, map[string]interface{}) string
	if rf, ok := ret.Get(0).(func(string) func(string, map[string]interface{}) string); ok {
		r0 = rf(lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(string, map[string]interface{}) string)
		}
	}

	return r0
}

// MockManager_TranslateFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateFunc'
type MockManager_TranslateFunc_Call struct {
	*mock.Call
}

// TranslateFunc is a helper method to define mock.On call
//   - lang string
func (_e *MockManager_Expecter) TranslateFunc(lang interface{}) *MockManager_TranslateFunc_Call {
	return &MockManager_TranslateFunc_Call{Call: _e.mock.On("TranslateFunc", lang)}
}

func (_c *MockManager_TranslateFunc_Call) Run(run func(lang string)) *MockManager_TranslateFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_TranslateFunc_Call) Return(_a0 func(string, map[string]interface{}) string) *MockManager_TranslateFunc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_TranslateFunc_Call) RunAndReturn(run func(string) func(string, map[string]interface{}) string) *MockManager_TranslateFunc_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
